---
title: "Weekly Guides"
author: "Econ 372: Economics of Health Care Markets"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Overview 
Here, I provide a guide for each week of class. I will post a new guide each week. The goal of each guide is simply to highlight the material for that week. By the end of the semester, this should be one large file that you can easily navigate to see what was done during each week of class.

# Week 1: Welcome!
Welcome to Economics of Health Care Markets! We're going to have a great time this semester and learn a ton about economics, health care, and health policy.

### Objectives for this week
- Recall the total annual expenditures on health and health care in the U.S.
- Compare U.S. health expenditures and quality to that of other countries
- Explain the debate surrounding the role of prices in U.S. health care expenditures
- Summarize some of the unique economic features of the U.S. health care market
 

### Activities 
- Discussion of U.S. health care expenditures and quality
- Overview of class and introductions

### Resources 
- [Syllabus](Syllabus/Econ372-Syllabus.pdf)
- [Class Website](https://imccart.github.io/Econ-372)
- [Class Notes](01-Introduction/01-slides.html)
- [Basic Calculus Review](01-Introduction/practice_problems.pdf) and [answers](01-Introduction/practice_problems_solutions.pdf)
- Some extra stuff:
  - Arrow, Kenneth J. 1963. ["Uncertainty and the Welfare Economics of Medical Care."](https://www.jstor.org/stable/1812044?seq=1#metadata_info_tab_contents) American Economic Review, 53(5)
  - Anderson, G., U. Reinhardt, P. Hussey, and V. Petrosyan. 2003. ["It's the prices, stupid: Why the United States is so different from other countries."](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.22.3.89) Health Affairs, 22(3)
  - Healthcare triage videos: [The Healthcare System of the United States](https://www.youtube.com/watch?v=yN-MkRcOJjY) and [Why Does the US Spend So Much On Healthcare?](https://www.youtube.com/watch?v=tFtAohYPSFc)
  - Time, 2013. [Bitter Pill: Why Medical Bills are Killing Us](https://time.com/198/bitter-pill-why-medical-bills-are-killing-us/)
  - Forbes, 2018. [Healthcare: It's the prices, stupid. Isn't it?](https://www.forbes.com/sites/elliekincaid/2018/03/13/healthcare-its-the-prices-stupid-isnt-it/#52a5fda3198a)
  - Blog, Random Critical Analysis, November 2018. ["Why everything you have said about the determinants of health expenditure is wrong in one million charts: A response to Noah Smith."](https://randomcriticalanalysis.com/2018/11/19/why-everything-you-know-about-healthcare-is-wrong-in-one-million-charts-a-response-to-noah-smith/)
  
  
# Week 2: Understanding risk
Welcome back! This week is all about risk and uncertainty. We will eventually use these concepts to study insurance markets and premiums.

### Objectives for this week
- Calculate expected values
- Define risk aversion and diminishing marginal utility
- Calculate and explain graphically the risk premium
 

### Activities
- Discussion of the health insurance *death spiral*
- In-class problem (expected values)
 

### Resources
- Textbook: Pindyk and Rubinfeld, Sections 5.1-5.2
- [Class Notes](02-Insurance/02-slides.html)
- CNN Business, February 2017, ["Humana pulls out of Obamacare for 2018"](https://money.cnn.com/2017/02/14/news/economy/humana-obamacare-insurer/)


# Week 3: Insurance demand
Welcome back! This week we'll finish our discussion of risk premiums and apply these tools to examine demand for health insurance (i.e., willingness to pay for health insurance).

 
### Objectives for this week
- Explain and draw graphically how the risk premium varies with the curvature of the utility function, probability of illness, and amount of potential loss
- Calculate risk premium and willingness-to-pay for health insurance
- Discuss viability of high-risk pools
 

### Activities
- Discussion forum on [Canvas](https://canvas.emory.edu/courses/70035)
- In-class problem (demand for health insurance)


### Resources
- Textbook: Sloan and Hsieh, Sections 4.1-4.7 (Chapter 4 available on [Canvas](https://canvas.emory.edu/courses/70035))
- Kaiser Family Foundation, February 2017, ["High-Risk Pools for Uninsurable Individuals"](https://www.kff.org/health-reform/issue-brief/high-risk-pools-for-uninsurable-individuals/)
- ESPN, January 2019, ["A New Threat: An Evaporating Insurance Market"](https://www.espn.com/espn/story/_/id/25776964/insurance-market-football-evaporating-causing-major-threat-nfl-pop-warner-colleges-espn)
 

# Week 4: Adverse selection
Welcome back! This week we'll broaden our study of insurance purchasing to the market level and study how the presence of adverse selection can affect insurance markets and premiums.

### Objectives for this week
- Explain and draw graphically a simplified insurance market with adverse selection
- Calculate the insurer loss or profit at a given price
- Calculate the equilibrium price in the market under some assumptions on insurer profitability
- Solve for the subsidy amount or penalty amount that would ensure full insurance in a market
 

### Activities
- In-class problem (adverse selection)
- Case study of New Jersey

 
### Resources
- Textbook: Pindyk and Rubinfeld, Section 17.1
- Sloan and Hsieh, Sections 4.8-4.10 (Chapter 4 available on [Canvas](https://canvas.emory.edu/courses/70035))
- Einav, L. and A. Finkelstein. 2011. ["Selection in Insurance Markets: Theory and Empirics in Pictures,"](https://www.aeaweb.org/articles?id=10.1257/jep.25.1.115) 25(1):115-138.
- NPR, December 2018, ["Short-Term Health Plans Boost Profits for Brokers and Insurers."](https://www.npr.org/sections/health-shots/2018/12/21/678605152/short-term-health-plans-boost-profits-for-brokers-and-insurers)
 


# Week 5: Insurance policy
This week concludes our study of health insurance. We'll finish this module with a discussion of some real world issues related to health insurance markets in the U.S.

 
### Objectives for this week
- Explain the history of the employer-provided health insurance market in the U.S.
- Define community ratings and discuss its costs and benefits for insurance markets
- Define risk-adjustment and its relevance to insurance markets
 

### Activities
- Discussion forum on [Canvas](https://canvas.emory.edu/courses/70035)
 

### Resources
- Commonwealth Fund, July 2018, ["The Effect of Eliminating the Individual Mandate Penalty."](https://www.commonwealthfund.org/publications/fund-reports/2018/jul/eliminating-individual-mandate-penalty-behavioral-factors)


# Week 6: Agency problems
 
We're starting a new module this week related to physician treatment decisions. Just as asymmetric information between patients and insurance companies was a big part of the adverse selection problem, this module will show how asymmetric information between physicians and patients can also create some interesting dynamics and incentives.

### Objectives for this week

- Explain the principal-agent problem in the context of medical care
- Define fee-for-service and capitated payment models
- Solve for treatment levels under fee-for-service and capitated payments
 

### Activities
- In-class problem (physician agency)

### Resources
- Textbook: Pindyk and Rubinfeld, Section 17.4
- McGuire, Thomas. 2000. ["Physician Agency,"](https://www.sciencedirect.com/science/article/abs/pii/S1574006400801687) Handbook of Health Economics, Volume 1.
- [The Dartmouth Atlas](https://www.dartmouthatlas.org/interactive-apps/)
- The Atlantic, December 2013, ["You're Getting Too Much Healthcare](https://www.theatlantic.com/health/archive/2013/12/youre-getting-too-much-healthcare/281896/)
- MIT News Office, June 2018, ["The value of late-in-life health care spending"](http://news.mit.edu/2018/value-late-life-health-care-spending-medicare-0628)
 

# Week 7: Agency and payments
 
This week we'll continue our study of physician agency and treatment decisions, focusing in particular on fee-for-service versus "capitated" payments.

### Objectives for this week

- Define fee-for-service and capitated payment models
- Compare treatment levels under fee-for-service and capitated payments
 
### Activities
- In-class problem (agency and fixed prices)
- Discussion forum on [Canvas](https://canvas.emory.edu/courses/70035)

### Resources
- Textbook: Pindyk and Rubinfeld, Section 17.4
- McGuire, Thomas. 2000. ["Physician Agency,"](https://www.sciencedirect.com/science/article/abs/pii/S1574006400801687) Handbook of Health Economics, Volume 1.


# Week 8: Exam week!

We have our exam this week on Wednesday, 3/4, and the exam will cover all material to date. We'll review and discuss the exam on Monday. 

Resources to prepare fo the exam include:

1. [Homework 1](homework/hwk-1/hwk1-instructions.html), with the answer key available on Canvas.
2. [Homework 2](homework/hwk-2/hwk2-instructions.html), with the answer key available on Canvas.
3. [Exam review sheet](exams/exam1-review.html)
4. [In-class problems](worksheets.html)


# Week 9: Hospital pricing

Hey class! This week is the start of a brand new process, and it comes alongside a slew of uncertainty in many other dimensions of our daily lives. One of the most important things going forward...let's all be patient with each other. Many of us (myself include) are dealing with other changes and disruptions. But we will work together and get through this!

In terms of class material, this week starts our third and final section of material related to hospital pricing. 

### Objectives for this week
The broad goals for this week are to review the mid-term and finish the **Motivation** and **What do hospital's maximize** sections of the [hospital pricing slides](04-Pricing/04-slides.html). More specifically, by the end of this week everone should be able to:<br>

1. Define and explain the differences between hospital prices, charges, and costs
2. Understand variation in hospital pricing and investigate price variation with the Health Care Pricing Project materials
3. Define and contrast a for-profit and not-for-profit hospital
4. Assess the merits and potential pitfalls of the criteria for a not-for-profit hospital

### Activities and materials
These activities are intended to facilitate an engaged "virtual" classroom on Zoom. Each activity or set of activities will align with pre-recorded materials. The goal is to watch the pre-recorded materials, spend 10-20 minutes on the relevant activities, and then join the live Zoom classroom to participate in the group discussion. We also have a new discussion forum (Discussion 4) this week on [Canvas](https://canvas.emory.edu/courses/70035).<br>

**Monday, March 23**<br>

- Mid-term exam answer key on [Canvas](https://canvas.emory.edu/courses/70035)
- Pre-recorded material: 
  - [Exam review](https://drive.google.com/open?id=1I5-ndYPXVbapdiWwgER-M2AIpcRi2Un8)
  - [3/23, Part I - What is a hospital price?](https://youtu.be/Y7v3HnFmhdo)
  - [3/23, Part II - Price variation](https://youtu.be/8QSQc9s2VeY)
- Virtual class questions:
  - Any questions about the mid-term?
  - What do we mean when we say hospital "price"?
  - What factors do you think can explain the differences in hospital prices (even for homogeneous products like MRIs)?
- [Recorded Zoom class](https://drive.google.com/file/d/1Z-Mb-fPrqfM5jNmsYhBeqK63bH9M0Kly/view?usp=sharing)<br>


**Wednesday, March 25**<br>

- Pre-recorded material
  - [3/25, Part I - Defining not-for-profit](https://youtu.be/kXdDQa89Uks)
  - [3/25, Part II - Community benefits](https://youtu.be/cninWUmm6Iw)
- Virtual class questions:
  - What does it mean to be a not-for-profit hospital?
  - What requirements are there to be a not-for-profit hospital?
  - Is our measure of "community benefit" for not-for-profit hospitals sufficient? 
  - How might the tax treatment of a not-for-profit allow those hospitals to set lower prices compared to for-profit hospitals?
- [Recorded Zoom Class](https://drive.google.com/file/d/1qCzvIbdslImAnC2fSrq36S7XQnzwxf0M/view?usp=sharing)


### Supplemental resources
- Textbook: 
  - Sloan and Hsieh, Sections 6.1-6.3 (Chapter 6 available on [Canvas](https://canvas.emory.edu/courses/70035))
  - Pindyk and Rubinefled, Sections 10.1-10.3, 12.1
- Reinhardt, Uwe. 2006. ["The Pricing of US Hospital Services: Chaos Behind a Veil of Secrecy."](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.25.1.57) *Health Affairs*, 25(1):57-69.
- ["Value of tax breaks for non-profit hospitals doubled in a decade,"](https://www.washingtonpost.com/national/health-science/value-of-tax-breaks-for-nonprofit-hospitals-doubled-in-a-decade/2015/06/17/4162c640-1450-11e5-9ddc-e3353542100c_story.html) *Washington Post*, 2015
- ["Nonprofit hospitals' community benefit requirements,"](https://www.washingtonpost.com/national/health-science/value-of-tax-breaks-for-nonprofit-hospitals-doubled-in-a-decade/2015/06/17/4162c640-1450-11e5-9ddc-e3353542100c_story.html) *Health Affairs* policy brief, 2016
- [Health Care Pricing Project](https://healthcarepricingproject.org/)



# Week 10: Hospital competition

This week we continue our coverage of hospital pricing, focusing on the role of competition and mergers.

### Objectives for this week
The broad goal for this week is to finish the **Pricing and Negotiations** section of the [hospital pricing slides](04-Pricing/04-slides.html). By the end of this week everone should be able to:<br>

1. Explain how we model pricing for not-for-profit hospitals and distinguish this from the for-profit framework
2. Solve for a profix maximizing price and quantity in a monopolist or monopolistic competition setting
3. Describe the hospital negotiation process as a Nash bargaining problem and solve a simple version of a Nash bargaining model
4. Explain the role of competition on pricing and describe how we measure competition in health care


### Activities and materials
These activities are intended to facilitate an engaged "virtual" classroom on Zoom. Each activity or set of activities will align with pre-recorded materials. The goal is to watch the pre-recorded materials, spend 10-20 minutes on the relevant activities, and then join the live Zoom classroom to participate in the group discussion. We also have a new discussion forum (Discussion 5) this week on [Canvas](https://canvas.emory.edu/courses/70035).<br>

**Monday, March 30**<br>

- Pre-recorded material:
  - [3/30 Part I - Pricing basics](https://youtu.be/RKNZOlXqbI0)
  - [3/30 Part II - Negotiated prices](https://youtu.be/E9htrWZv9z0)
- Virtual class questions:
  - Solve for the profit maximizing price and quantity for a monopolistically competitive firm, [practice problem on unilateral pricing](worksheets.html)
  - Solve for a [Nash bargaining problem](worksheets.html)
- [Recorded Zoom class](https://drive.google.com/open?id=1As8XrN6Tic9NqPNid1VcwxwFEgpfTEYc)<br>


**Wednesday, April 1**<br>

- Pre-recorded material
  - [4/1 Part I - Measuring competition](https://youtu.be/y2nMEOcMxeI)
  - [4/1 Part II - Competition trends](https://youtu.be/8T04Q1yA550)
- Virtual class questions:
  - Why do we use the HHI? Are there any benefits or problems with its use as a measure of hospital competitiveness?
  - How has hospital concentration changed over time and what have been the effects on pricing and quality?
- [Recorded Zoom class](https://drive.google.com/open?id=1fngrl41fxLhFhqsg9KYr7Iu81fnByRMy)


### Supplemental resources
- [Health Care Cost Institute, Healthy Marketplace Index](https://healthcostinstitute.org/research/hmi-interactive)
- ["Making healthcare markets work: Competition policy for health care"](https://www.brookings.edu/research/making-health-care-markets-work-competition-policy-for-health-care/)
- [Hearing on health care consolidation and anticompetitive conduct](https://www.youtube.com/watch?v=c2rLy4FWn_g). Please focus just on the testimony of Martin Gaynor, as this is most relevant for our class. But if you're interested in pharmaceuticals, there is some great content in this video from other members of the panel as well.


# Week 11: Fixed Prices

This week we continue our coverage of hospital pricing, where we'll introduce Medicare and Medicaid and discuss the role of competition with fixed prices.

### Objectives for this week
The broad goal for this week is to finish the **Fixed Prices** section of the [hospital pricing slides](04-Pricing/04-slides.html). By the end of this week everone should be able to:<br>

1. Describe the Medicare program and its components
2. Differentiate between how Medicare Part A and Medicare Part B are funded
3. Describe Medicaid and distinguish it from Medicare
4. List and explain two ways in which the ACA changed Medicaid


### Activities and materials
These activities are intended to facilitate an engaged "virtual" classroom on Zoom. Each activity or set of activities will align with pre-recorded materials. The goal is to watch the pre-recorded materials, spend 10-20 minutes on the relevant activities, and then join the live Zoom classroom to participate in the  group discussion. We also have a new discussion forum (Discussion 6) this week on [Canvas](https://canvas.emory.edu/courses/70035) related to the economics of the coronavirus.<br><br>

**Monday, April 6**<br>

- Pre-recorded material:
  - [4/6 Medicare](https://drive.google.com/open?id=1JAPl0dCe8k7ZJrcoZCUONEnCj7vW6TVU)
  - In addition to the video, please try to listen to the [All About Medicare](https://open.spotify.com/episode/11QshS7vlTptfBVkV8WkTG?si=sCnpjaDNT5mF3lDC6obB4g) Podcast from Kaiser Health News.
- Virtual class questions:
  - What is the difference between Medicare Parts A and B?
  - What are some benefits and potential costs of relying on private insurers in the Medicare Advantage program?
  - True or false: Medicare pays for health care in a nursing home or skilled nursing facility.
- [Recorded Zoom class](https://drive.google.com/open?id=1nil95AyqBcv7lNMaqGqvxyJdjdTLC2tk)


**Wednesday, April 8**<br>

- Pre-recorded material
  - [4/8 Medicaid](https://youtu.be/z235X8R5RT8)
  - In addition to these resources, please try to listen to the [All About Medicaid](https://open.spotify.com/episode/5wV95SFHGv9trpZrXACELP?si=DFnzeWj7R1eIv9w2Xr3PtQ) Podcast from Kaiser Health News.
- Virtual class questions:
  - What do people mean when they say "Medicaid Expansion" in the context of the ACA?
  - True or false: Medicaid is insurance for low income people and Medicare is insurance for senior citizens.
- [Recorded Zoom class](https://drive.google.com/open?id=1wqtKAnEA7cdzaQ5iOxsmfpwM3jV53GS2)


### Supplemental resources
- [All About Medicare, Podcast](https://open.spotify.com/episode/11QshS7vlTptfBVkV8WkTG?si=sCnpjaDNT5mF3lDC6obB4g)
- [All Aboud Medicaid, Podcast](https://open.spotify.com/episode/5wV95SFHGv9trpZrXACELP?si=DFnzeWj7R1eIv9w2Xr3PtQ)


# Week 12: Two-price Market

This week we continue our coverage of hospital pricing to a model of a for-profit hospital that sets their own price in the private market and receives a fixed price in the public insurance market.

### Objectives for this week
The broad goal for this week is to finish the **Two-price Market** section of the [hospital pricing slides](04-Pricing/04-slides.html). By the end of this week everone should be able to:<br>

1. Use our two-price model to predict the effect of a change in public (e.g. Medicare or Medicaid) prices
2. Identify the minimum price at which public insurance patients lose access to care
3. Define cost-shifting and summarize the key aspects of the cost-shifting debate


### Activities and materials
These activities are intended to facilitate an engaged "virtual" classroom on Zoom. Each activity or set of activities will align with pre-recorded materials. The goal is to watch the pre-recorded materials, spend 10-20 minutes on the relevant activities, and then join the live Zoom classroom to participate in the group discussion. We also have a new discussion forum (Discussion 5) this week on [Canvas](https://canvas.emory.edu/courses/70035).<br>

**Monday, April 13**<br>

- Pre-recorded material:
  - [4/13 Two-price Market](https://youtu.be/US-LYZH5qp0)
- Virtual class questions:
  - Solve the practice problem on the [two-price model](worksheets.html)
- [Recorded Zoom class](https://drive.google.com/open?id=1tvPIdk5C8GsFxcPgHqVx_-Nuc57-SdYc)


**Wednesday, April 15**<br>

- Pre-recorded material:
  - [4/15 Cost-shifting](https://youtu.be/Alsk1C34hSw)
- Virtual class questions:
  - What is cost-shifting and how does it differ from price discrimination? 
  - Why are some researchers skeptical that cost-shifting occurs?
- [Recorded Zoom class](https://drive.google.com/open?id=1QI1BJFO-6EFt5nw5PqnHE6UMS_E2qnMY)


### Supplemental resources
- Textbook: Sloan and Hsieh, Section 5.4
- ["History of Cost Shifting"](https://theincidentaleconomist.com/wordpress/hospital-cost-shifting-brief-history-and-possible-future/)


# Week 13: Payment Policies

This week we will conclude our discussions of hospital pricing and payments, focusing on recent policy events including pay-for-performance and capitated payment models. We discussed these briefly in our physician agency models but now we will talk about them in the context of hospital prices. 

### Objectives for this week
The broad goal for this week is to finish the **Current Policy Issues** section of the [hospital pricing slides](04-Pricing/04-slides.html). By the end of this week everone should be able to:<br>

1. Explain at least one recent hospital pay for performance program
2. Identify and explain two pros and two cons from healthcare pay for performance models
3. Define a capitated payment and describe at least one type of capitated payment currently in the U.S.
4. Discuss the merits and drawbacks of a capitated payment model


### Activities and materials
These activities are intended to facilitate an engaged "virtual" classroom on Zoom. Each activity or set of activities will align with pre-recorded materials. The goal is to watch the pre-recorded materials, spend 10-20 minutes on the relevant activities, and then join the live Zoom classroom to participate in the group discussion. Note that my slides for this material just list a few of the programs, so there are no pre-recorded "lectures" for this week. Instead, I've posted a couple of specific resources (videos, papers, etc.) that will help to facilitate a good class disucssion.

**Monday, April 20**<br>

- Pre-recorded material and resources:
  - [Healthcare Triage, Pay for Performance](https://www.youtube.com/watch?v=SFNuztrgQY0)
  - [NEJM Report, What is Pay for Performance](https://catalyst.nejm.org/doi/full/10.1056/CAT.18.0245)
- Virtual class questions:
  - List two questions regarding the implementation of the value-based purchasing program
  - Summarize the effects of the value-based purchasing program and the hospital readmission reduction program on hospital spending
  - Identify how your local hospital is affected by the readmission reduction program using the Kaiser Health News tool [here](https://khn.org/paying-for-hospital-quality/).
- [Recorded Zoom class](https://drive.google.com/open?id=1qO7Wgxkhvl-A7GNERqjLiI_ud4lm1Euj)


**Wednesday, April 22**<br>

- Pre-recorded material and resources:
  - [Unlocking Accountable Care Podcast](https://www.healthcarenowradio.com/programs/unlocking-accountable-care/)
  - [NEJM Report, What Are Bundled Payments](https://catalyst.nejm.org/doi/full/10.1056/CAT.18.0247)
  - [The Incidental Economist](https://theincidentaleconomist.com/wordpress/can-paying-for-a-health-problem-as-a-whole-not-piece-by-piece-save-medicare-money/)
- Virtual class questions:
  - What do we mean by "accountable care" in the context of U.S. health policy?
  - What effects have bundled payments had on hospital outcomes?
- [Recorded Zoom class](https://drive.google.com/open?id=1HjLqG0lZEoKv2zE1yDIrWuJXrQIJYpTN)


# Week 14: Case Study

We made it! This is the final week of class (and the last day of the semester). Today (4/27) is an opportunity for you to ask some questions about your case study. I'll start our zoom class as usual around 9:00am eastern, but please come with any questions ready. You can either ask your questions directly or submit them through the zoom chat feature...whatever is your preference. 

**Monday, April 27**<br>
- One last video (link pending)
- Recorded Zoom class (link pending)