---
title: "Homework 2: Physician and Treatment Decisions"
author: "Econ 372: Economics of Health Care Markets"
date: "Due: Wednesday, February 26, 2020"
output: 
  bookdown::html_document2:
    toc: FALSE
    toc_float: FALSE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

<br>
This is our second homework assignment of the semester. It covers questions related to physician treatment decisions and asymmetric information. You can turn in handwritten or typed answers, but if you're submitting handwritten answers, please take time to make your work and answers readable. Please also staple all of your answers together. 5 points will be deducted for assignments turned-in without a staple.

<br>
<br>

1. Assume a physician is operating with the standard profit function, $\pi = (p-c)x$, where $c$ reflects a constant marginal cost of production, $x$ denotes quantity of healthcare provided, and $p$ denotes the price per unit of healthcare provided. Assume also that patients receive some total benefit from care received, reflected by the equation $B(x)=10x - (1/2)x^{2}$. Patients must pay the full price, $p$, of any care received, so that the net benefit of care to the patient is then $B(x)-px$ (their total benefit less their costs). Finally, assume that the best outside option for the patient yields a net benefit of 8.<br><br>
    + If the patient were to choose $x$ to maximize their net benefit, what level of $x$ would they choose?<br>
    
    + Find the physician's profit maximizing choice of quantity, $x$. You need to solve this as a function of $c$.<br>
    
    + At a marginal cost of $c=2$, find the physician's optimal price, $p$.<br>
    
    + Compare the physician's profit maximizing choice of $x$ to the patient's optimal choice of $x$. Are these the same? Why or why not?<br>

<br>
<br>

2. Assume instead that the physician faces a fixed price, $\bar{p}=4$. The setup is otherwise identical to question 1.<br><br>
    + If the patient were to choose $x$ to maximize their net benefit, what level of $x$ would they choose?<br>
    
    + Again assuming $c=2$, find the physician's profit maximizing choice of quantity, $x$. Hint: marginal cost doesn't matter here except to ensure that $c<\bar{p}$.<br>    
    
    + How does the deviation in the physician and patient optima differ from what you found in question 1? Explain your answer in a couple of sentences.<br>


<br>
<br>

3. Assume now that the physician can affect the number of their patients through their influence on the net benefit (NB) provided to patients. Assume also that the physician faces a fixed price paid by the insurer, denoted $p_{s}$, along with a capitated payment per patient, $R$, and that the patient faces a price of <span>&#36;</span>0, $p_{d}=0$. In this extension, the physician's goal is to choose $x$ so as to maximize profit, $$\pi = n\left(NB\right) \left[R + (p_{s}-c)x \right].$$ Finally, assume the functional forms $n(NB)=\sqrt{NB}$ and $B(x)=10x-x^{2}$.<br><br>
    + Find the patient's optimal level of $x$.<br>
    
    + Find the first order condition for the physician's choice of $x$. Don't try to solve this for $x$.<br>
    
    + Assuming that the physician makes <span>&#36;</span>1 on each quantity of care provided ($p_{s}-c=1$), find the value of the capitated payment, $R$, such that overtreatment is minimized. Please assume that $x$ can only take discrete values, so that the minimum amount of overtreatment is 1 "unit of care" per patient.<br>
    
    + Assuming that the physician loses <span>&#36;</span>1 on each quantity of care provided ($p_{s}-c=-1$), find the value of the capitated payment, $R$, such that undertreatment is minimized. Again, assume that $x$ can only take discrete values, so that the minimum amount of undertreatment is 1 "unit of care" per patient.<br>
    
    + Which scenario (minimizing overtreatment or undertreatment) is better for the physician's profit.<br>
    
